### PR TITLE
feat: upgrade PySwitchbot requirement and expose light and battery information

### PR DESCRIPTION
**Pull request by erozqba**
Thanks a lot for this awesome little project! It saves me a lot of time integrating the switch-bot curtains into HA.

This changes should help in resolving the issues https://github.com/alextud/ha-switchbot-curtain/issues/2 and https://github.com/alextud/ha-switchbot-curtain/issues/8

Changelog:
 - Update PySwitchbot requirement to version 0.10.0
 - Update code to use the new class SwitchbotCurtain
 - Expose light and battery information

### CODE REVIEW

**Comment by alextud** [comment]
Hey Ernesto, thanks for improving this integration.

I get **171** for the battery field is that correct, do you get same value ? 
On the switchbot app, battery value is 43%

**Comment by erozqba** [comment]
Hi @alextud 
I get the same lecture on the battery on HA and the switch-bot app

image

But the light-sensor shows different values. I found the values shows by the switch-bot app are rounded and not very accurate. They try to show an average by hours and days, I prefer the one on HA because it give me more flexibility to set up automation than the ones on the switch-bot app.

I had no issues so far after upgrading the PySwitchbot requirement to version 0.10.0.

My switch-bot curtains were bought very recently, like 1 week ago.

**Comment by TL-HA** [comment]
Hi thank-you for doing this.  I also see 3digits in the battery attribute of the switch entity eg 194, 215 etc.  A gauge card would be nice but they only seem to work with sensors.

**Comment by erozqba** [comment]
@TL-HA These attributes appeared automatically on my case. I'm using the docker version of HA:

```

Version | core-2021.5.4
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 4.15.0-143-generic
CPU Architecture | x86_64


```

My switch-bot curtains `firmware version is V3.1`

**Comment by TL-HA** [comment]
Thanks, just worked it out need to click in the entity card and the additional info pops up. im on firmware v3.11, core-2021.4.5 on a pi.  It should be easy to cross reference the % in the app to work out the various 3 digits = %.  Many thanks.

**Pull request merged**
